### ISSUE TITLE
Youtube API v2 expired!

### ISSUE THREAD

**Issue by moay** [sseffa/laravel-video-api#8]
Will you upgrade to the new v3 API?

**Comment by vadimwe** [comment]
+1 @sseffa ?

**Comment by sseffa** [comment]
want to upgrade but got no time for it

**Comment by vadimwe** [comment]
Any forecast about it?

**Comment by sseffa** [comment]
1-2 months

**Comment by vadimwe** [comment]
Thank you mate!

**Comment by vadimwe** [comment]
Thank you for update! But youtube video still not found... for example video id: 6hmKTaXvMuA
https://www.youtube.com/watch?v=6hmKTaXvMuA

**Comment by sseffa** [comment]
You should take an api  key from google developer site and allow your own IP adress

**Comment by vadimwe** [comment]
I have api key, but can`t find IP address setup

**Comment by sseffa** [comment]
![screenshot_14](https://cloud.githubusercontent.com/assets/2960378/11871889/0bb5a62c-a4db-11e5-8d67-b172e4e1eec2.png)

**Comment by vadimwe** [comment]
No luck - Video not found.

**Comment by sseffa** [comment]
before running here https://developers.google.com/youtube/v3/docs/channels/list, then try my package
